config/routes.rb
Rails.application.routes.draw do
  get '/auth/google_oauth2/callback', to: 'sessions#google'
  root to: 'sessions#welcome'
  resources :klasses do
    resources :user_klasses
  end
  resources :users, only: [:new, :create, :show, :edit, :update]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  delete '/session', to: 'sessions#destroy'
  get '/user/:user_id/user_klasses', to: 'user_klasses#index', as: 'user_user_klasses' 
  get '/user/:user_id/user_klasses/:id', to: 'user_klasses#show', as: 'user_user_klass'
  delete'/user/:user_id/user_klasses/:id', to: 'user_klasses#destroy'
  #get '/register', to: 'user_klasses#new'
  #post '/register', to: 'user_klasses#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/klass.rb
class Klass < ApplicationRecord
    has_many :user_klasses
    has_many :users, through: :user_klasses
    validates :name, presence: true
    validates :instructor, presence: true
    validates :scheduled_time, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :user_klasses
    has_many :klasses, through: :user_klasses
    validates :email, presence: true
    validates :email, uniqueness: true
    #validates :name, presence: true
    validates :username, presence: true
    validates :username, uniqueness: true
    validates :password, presence: true
    scope :instructors, -> { where(instructor: true) }
end

app/models/user_klass.rb
class UserKlass < ApplicationRecord
    belongs_to :user
    belongs_to :klass
end

app/controllers/Admin/instructor_controller.rb
class Admin::InstructorController < ApplicationController
    def instructor
         if current_user = user.instructor(true)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authorized
    helper_method :current_user
    helper_method :logged_in?
    helper_method :instructor

    def current_user    
        User.find_by(id: session[:user_id])  
    end

    def logged_in?
        !current_user.nil?  
    end
    
    def authorized
        redirect_to '/welcome' unless logged_in?
    end

    def instructor
        current_user.instructor
    end


end

app/controllers/klasses_controller.rb
class KlassesController < ApplicationController
    before_action :set_class, only: [:show, :edit, :update, :destroy]

    
      def index
        @klass = Klass.order(:name)
      end
    
      def show
      end

      def new
        if instructor
        @klass = Klass.new
        else
          redirect_to '/welcome'
        end
      end
    
      def create
        @klass = Klass.new(klass_params)
         if @klass.save
        #byebug
        redirect_to klasses_path(@klass)
         end
      end

      def edit
        if instructor
          else
          redirect_to '/welcome'
        end

      end
    
      def update
        @klass.update(klass_params)
        redirect_to klass_path(@klass)
        
      end
    
      def destroy
        
        if @klass.destroy
          redirect_to klasses_path
        else
          flash[:notice] = "Was unable to delete class!"
          redirect_to @klass
        end
      end
      
      private

      def set_class
        @klass = Klass.find(params[:id])
      end

      def klass_params 
         params.require(:klass).permit(:name, :instructor, :scheduled_time)
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :authorized, only: [:new, :create, :welcome, :google]
    def new
    end

    def login
    end

    def create
       @user = User.find_by(username: params[:username])
       if @user && @user.authenticate(params[:password])
          session[:user_id] = @user.id
          redirect_to '/welcome'
       else
         @errors = "Username and/or Password is incorrect."
          render :new
       end
    end

    def destroy
        session.clear
        redirect_to '/welcome'
    end

    def google
      
      @user = User.find_or_create_by(email: auth["info"]["email"]) do |user|
        user.name= auth["info"]["first_name"]
        user.username= auth["info"]["name"]
        user.password= SecureRandom.hex(20)
      
   end
    
    if @user && @user.id
      session[:user_id] = @user.id
       redirect_to welcome_path
     else
        redirect_to welcome_path
      end
    end
   
    private

    def auth
      request.env['omniauth.auth']
    end

  end

app/controllers/user_klasses_controller.rb
class UserKlassesController < ApplicationController
  
    def new
        set_klass
        @uk = @klass.user_klasses.build
    end

    def create 
        if params[:klass_id]
            set_klass
            @uk = current_user.user_klasses.build(klass_id: params[:klass_id],reminder: params[:user_klass][:reminder])
          else 
        @uk = UserKlass.new(uk_params)
          end
          #byebug
        if @uk.save
       redirect_to user_path(current_user)
        end
      #  if @uk.reminder == true
        #    UserMailer.reminder(current_user).deliver_now
        #end
    
    end

    def index
       # byebug
        if current_user == User.find_by_id(params[:user_id])
        @user = User.find_by_id(params[:user_id])
        
        @user_klasses = @user.user_klasses
        else
            redirect_to '/welcome'
        end
    end

    def show 
        #byebug
        @user_klasses = UserKlass.find(params[:id])
        if current_user.id == @user_klasses.user_id
            else
                redirect_to '/welcome'
            end
      
    end

    
    def destroy
        @user_klass = UserKlass.find(params[:id])
        if current_user.id == @user_klass.user_id
         @user_klass.destroy
          redirect_to user_user_klasses_path(current_user)
        else
          redirect_to user_user_klasses_path(current_user)
        end
      end

    private 

    def uk_params
        params.require(:user_klass).permit(:user_id, :klass_id, :reminder) 
    end

    def set_klass
      @klass = Klass.find_by_id(params[:klass_id])
    end
   
   
   

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authorized, only: [:new, :create]
    before_action :set_user, only: [:show, :update, :edit]


def new
   @user = User.new 
end

def create 
    @user = User.new(user_params)
        if @user.save
        session[:user_id] = @user.id
        redirect_to '/welcome'
    else
        @errors = @user.errors.full_messages.uniq
           render new_user_path
        end
end

def show 
    #byebug
    @user = User.find(params[:id])
    @klass = Klass.all
    #byebug
end

def edit
end

def update
    
  if @user.update(user_params)
  #byebug
  redirect_to user_path(@user)
else
    @errors = @user.errors.full_messages.uniq
       render '/users/edit'
    end
end

private

def set_user
    @user = current_user
end

def user_params
    params.require(:user).permit(:username, :password, :email, :name, :age, :skill_level, :instructor)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/klasses_helper.rb
module KlassesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/klasses/_form.html.erb
  <label>Class:</label><br>
  <%= c.text_field :name %><br>

  <label>Instructor:</label><br>
  <%= c.text_field :instructor %><br>

  <label>Day/Time:</label><br>
  <%= c.text_field :scheduled_time %><br>

app/views/klasses/edit.html.erb
<h3>Update Class</h3>

<%= form_for(@klass) do |c| %>

<%= render 'form', c: c%>

  <%= c.submit %>
<% end %>

app/views/klasses/index.html.erb
<h1>Class List</h1>

<% @klass.each do |klass| %>
	<li><%=link_to klass.name, klass_path(klass) %></li>
<% end %>
<br>
<%if current_user.instructor%>
<%= button_to "Create Class", '/klasses/new' , method: :get%>
<%end%>

app/views/klasses/new.html.erb
  
<h3>Create Class</h3>

<%= form_for(@klass) do |c| %>
  <label>Class:</label><br>
  
  <%= render 'form', c: c%>

  <%= c.submit %>
<% end %>

app/views/klasses/show.html.erb
<h1><%= @klass.name %></h1>

<p>Instructor: <%= @klass.instructor%></p>

<p>Schedule: <%= @klass.scheduled_time%></p>


<br>
<%= button_to "Register", new_klass_user_klass_path(@klass) , method: :get  %>

<%if current_user.instructor%>
<%= button_to "Edit", edit_klass_path(@klass), method: :get%>
<%= button_to "Delete", @klass , method: :delete, data: {confirm: "Are you sure?"} %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>StudentClassManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">LHC</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/welcome">Home <span class="sr-only">(current)</span></a>
        <%if logged_in?%>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=<%=user_path(current_user)%>>Your Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=<%=klasses_path%>>Classes</a>
      </li>
       <li class="nav-item">
        <a class="nav-link"<%= link_to "Log Out", '/session', method: :delete %></a>
        <%else%>
         </li>
      <li class="nav-item">
        <a class="nav-link"<%= link_to "Sign Up", '/users/new', method: :get%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Login", '/login', method: :get%></a>
        </li>
        <li class="nav-item">
        <a class="nav-link" <%= link_to "Login with Google", '/auth/google_oauth2'%></a>
      <%end%>
      </li>
    </ul>
  </div>
</nav>
  <body>
    <%= yield %>
    <img src="https://libertyhaganahcenter.com/wp-content/uploads/2020/05/liberty_haganah_logo2-300x300.png" alt="Girl in a jacket" style="width:300px;height:300px;">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

app/views/user_klasses/index.html.erb
<h1>Your Schedule</h1>

<%@user_klasses.each do |s|%>
<li><%=link_to s.klass.name, user_user_klass_path(s.klass_id, s.id ) %> <%= s.klass.scheduled_time %></li>
<%end%>

app/views/user_klasses/new.html.erb
<h1>Register for a Class!</h1>

<%= form_for @uk, url: klass_user_klasses_path(@klass) do |c| %>

    <%= c.label "Reminder?" %> <br />
    <%= c.check_box :reminder %> <br />
    <%= c.submit %> 
 <%end%>

app/views/user_klasses/show.html.erb
<h1> Your Class </h1>

Class: <%= @user_klasses.klass.name%>
<br>
Instructor: <%= @user_klasses.klass.instructor%>
<br>
Scheduled Time: <%= @user_klasses.klass.scheduled_time%>

<%= button_to "Delete", @user_klass , method: :delete, data: {confirm: "Are you sure?"} %>

app/views/users/_errors.html.erb
 <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being created:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

app/views/users/_form.html.erb
  <label>Email:</label><br>
  <%= f.text_field :email %><br>

  <label>Name:</label><br>
  <%= f.text_field :name %><br>

  <label>Username:</label><br>
  <%= f.text_field :username %><br>

  <label>Password:</label><br>
  <%= f.text_field :password %><br>

  <label>Age:</label><br>
  <%= f.text_field :age %><br>

  <label>Skill Level:</label><br>
  <%= f.text_field :skill_level %><br>

   <%= f.label "Instructor?" %> <br />
   <%= f.check_box :instructor %> <br />

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= form_for(@user) do |f| %>
 
 <%=render 'errors', f: f%>

  
  

<%= form_for @user do |f|%>

<%= render 'form', f: f %>

  <%= f.submit %>
<%end%>
<%end%>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for(@user) do |f| %>

<%=render 'errors', f: f%>

  

<%= form_for @user do |f|%>

<%= render 'form', f: f %>

  <%= f.submit %>
<%end%>
<%end%>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<p> Your Profile</p>
<p>Name: <%= @user.name %></p>
<p>Age: <%= @user.age %></p>
<p>Skill Level: <%= @user.skill_level %></p>


  
<h2><%=link_to "Your Schedule", user_user_klasses_path(current_user) %></h2>
<br>
<%= button_to "Edit", edit_user_path(@user), method: :get%>